name: SignPostPlus
main: signpostplus\SignPostPlus
version: 1.3
<<<<<<< HEAD
api: [3.0.0, 3.0.0-ALPHA12]
=======
api: [3.0.0, 3.0.0-ALPHA10 ,3.0.0-ALPHA11]
>>>>>>> 2ee091868fc47e667f07703937ab758a1a598338
load: POSTWORLD
authors:
 - OtorisanVardo
 - aieuo
<<<<<<< HEAD
 - Noi_noel
=======
>>>>>>> 2ee091868fc47e667f07703937ab758a1a598338
